### PR TITLE
add e2e test scripts in prow

### LINKED ISSUE #3: e2e test with prow
guide:  https://github.com/kubeflow/testing#adding-an-e2e-test-for-a-new-repository

### PR DESCRIPTION
**Pull request by everpeace**
fixes #3

@jlewi @gaocegege Would you mind reviewing this PR??  I added e2e test with prow by referring pytorch repo.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/chainer-operator/19)

### CODE REVIEW

**Comment by jlewi** [comment]
I opened kubeflow/kubeflow#1325 to make it easier to share code across E2E tests.

**Comment by jlewi** [comment]
Thanks. Please let me know when this is ready for another look.

**Comment by everpeace** [comment]
@jlewi I changed the script to use `kfctl.sh`.  Because I didn't run `kfctl.sh` actually,  there might be some mistakes.  Please take a look.  Thanks in advance 🙇

**Comment by jlewi** [comment]
It doesn't look like prow is triggering any tests. If you setup prow to run the presubmits then you will be able to verify as part of this PR that the tests are working correctly before you check them in.

**Comment by everpeace** [comment]
@jlewi I changed to use checkout.sh instead of downloading `kfctl.sh` and opened a PR in kubernetes/test-infra to activate prow in the repo.  PTAL 🙇

**Comment by jlewi** [comment]
I approved the other PR. As soon as the test is running and passing I think we can submit this PR.

**Comment by everpeace** [comment]
@jlewi Hi, I'm now struggling on `kfctl.sh init` step in `setup-cluster` argo step because below error:

```
++ gcloud projects describe kubeflow-ci '--format=value(project_number)'
ERROR: (gcloud.projects.describe) User [593963025935-compute@developer.gserviceaccount.com] does not
 have permission to access project [kubeflow-ci] (or it may not exist): Request had insufficient aut
hentication scopes.
+ PROJECT_NUMBER=
```
ref: http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-chainer-operator-presubmit-e2e-19-8c9c3fc-7-577d?tab=workflow&nodeId=kubeflow-chainer-operator-presubmit-e2e-19-8c9c3fc-7-577d-3717692062&sidePanel=logs%3Akubeflow-chainer-operator-presubmit-e2e-19-8c9c3fc-7-577d-3717692062%3A 

Would you mind giving me some advise??

**Comment by jlewi** [comment]
You're getting a permission error because you are relying on the VM service account which doesn't have sufficient scopes.

You need to do two things

1. You need to mount a secret into your steps and set the environment variable GOOGLE_APPLICATION_CREDNETIALS

Your argo workflow needs to define a volume corresponding to the secret in our kubeflow-ci cluster containing credentials for a GCP service account; see here
https://github.com/kubeflow/kubeflow/blob/master/testing/workflows/components/kfctl_test.jsonnet#L319

Your argo step template needs to add this secret as a volume mount like this
https://github.com/kubeflow/kubeflow/blob/master/testing/workflows/components/kfctl_test.jsonnet#L110

Then you need to set the environment variable GOOGLE_APPLICATION_CREDENTIALS to point to the secret like so
https://github.com/kubeflow/kubeflow/blob/master/testing/workflows/components/kfctl_test.jsonnet#L80

1. You need to activate the service account; by running the appropriate gcloud command see here
https://github.com/kubeflow/kubeflow/blob/master/testing/workflows/run.sh#L7

**Comment by everpeace** [comment]
@jlewi Thank you very much for helping me!  I'm now trying to finish e2e test work.  However,  I found `kfctl.sh delete platform` does NOT delete platform correctly: https://github.com/kubeflow/kubeflow/blob/master/scripts/kfctl.sh#L237-L258

I tried my e2e test so many times without knowing it... And, I finally got quota error in my e2e test.... 

```
message: "{\"ResourceType\":\"container.v1.cluster\",\"ResourceErrorCode\":\"403\"\
   ,\"ResourceErrorMessage\":{\"code\":403,\"message\":\"Insufficient regional quota\
   \ to satisfy request: resource \\\"CPUS\\\": request requires '16.0' and is short\
   \ '8.0'. project has a quota of '320.0' with '8.0' available.\",\"status\":\"\
   PERMISSION_DENIED\",\"statusMessage\":\"Forbidden\",\"requestPath\":\"https://container.googleapis.com/v1/projects/kub
eflow-ci/zones/us-east1-d/clusters\"\
   ,\"httpMethod\":\"POST\"}}"
```

So, would you mind deleting old existing cluster??? 🙇   Thank you in advance.

// I will squash my small commits when e2e test passed.

**Comment by everpeace** [comment]
@jlewi Thanks again for cleaning up garbages 🙇   Finally this pr become to be ready for review!!

But, there is one concern in clean-up job.  It seems that deleting service accounts failed by permission issue.  Could you give advice how to delete sevice accounts of the job correctly??

http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-chainer-operator-presubmit-e2e-19-444c6e2-32-3021?tab=workflow&nodeId=kubeflow-chainer-operator-presubmit-e2e-19-444c6e2-32-3021-566898882&sidePanel=logs%3Akubeflow-chainer-operator-presubmit-e2e-19-444c6e2-32-3021-566898882%3Amain

```
...
+ SA=z-19-444c6e2-32-3021-user@kubeflow-ci.iam.gserviceaccount.com
+ python /mnt/test-data-volume/kubeflow-chainer-operator-presubmit-e2e-19-444c6e2-32-3021/src/kubeflow/kubeflow/scripts/gke/delete_role_bindings.py
 --project=kubeflow-ci --service_account=z-19-444c6e2-32-3021-user@kubeflow-ci.iam.gserviceaccount.com
Service account z-19-444c6e2-32-3021-admin@kubeflow-ci.iam.gserviceaccount.com doesn't exist or you do not have permission to access service accoun
ts.
+ deleteSa z-19-444c6e2-32-3021-user@kubeflow-ci.iam.gserviceaccount.com
+ local SA=z-19-444c6e2-32-3021-user@kubeflow-ci.iam.gserviceaccount.com
++ gcloud --project=kubeflow-ci iam service-accounts describe z-19-444c6e2-32-3021-user@kubeflow-ci.iam.gserviceaccount.com
Service account z-19-444c6e2-32-3021-user@kubeflow-ci.iam.gserviceaccount.com doesn't exist or you do not have permission to access service account
s.
+ O='ERROR: (gcloud.iam.service-accounts.describe) PERMISSION_DENIED: Permission iam.serviceAccounts.get is required to perform this operation on s
ervice account projects/-/serviceAccounts/z-19-444c6e2-32-3021-user@kubeflow-ci.iam.gserviceaccount.com.'
+ local RESULT=1
```

**Comment by jlewi** [comment]
I think the error is expected; You unfortunately get the same error message if the service account doesn't exist.

**Comment by everpeace** [comment]
@jlewi I fixed my branch regarding your comments.  Please take a look.  Thanks in advance 🙇

**Comment by everpeace** [comment]
@jlewi Thanks!  I'm going to approve by myself this time.  I'll add you to OWNERS file later 👍

**Pull request merged**
